In [ ]:
import pandas
import sqlite3
import os

In [ ]:
path = r"Dados_gevac\OVITRAMPAS 2026\PLANILHA GERAL OVT 2026 ATÃ_ O CICLO  - ESSA É A NOVA PLNILHA DE DIGITAÇÃO DAS OVITRAMPAS.xlsx"
ovitrampas2026 = pandas.read_excel(path,0,header=0)

,Ano,CICLOS,DS,BAIRRO,BAIRRO_AREA,AGENTE / MATRICULA,QT,ID_OVT,DT_COLETA,DT_ENTREGA_APOIO,DT_ENTREGA_LAB,DT_LEITURA,NM_TEC_LAB,DT_DIG,DT_ENVIO_DS,N_OVOS,OBS
0,2026,1,I,RECIFE ANTIGO,RECIFE ANTIGO,EMERSON MELO/77.110-0,1,REC1001,2026-01-29,2026-01-30,2026-02-05,2026-02-07,ANA CAROLINA,2026-03-07 00:00:00,NaN,16,NaN
1,2026,1,I,RECIFE ANTIGO,RECIFE ANTIGO,EMERSON MELO/77.110-0,1,REC1002,2026-01-29,2026-01-30,2026-02-05,2026-02-07,ANA CAROLINA,2026-03-07 00:00:00,NaN,14,NaN
2,2026,1,I,RECIFE ANTIGO,RECIFE ANTIGO,EMERSON MELO/77.110-0,1,REC1003,2026-01-29,2026-01-30,2026-02-05,2026-02-07,ANA CAROLINA,2026-03-07 00:00:00,NaN,83,NaN
3,2026,1,I,RECIFE ANTIGO,RECIFE ANTIGO,EMERSON MELO/77.110-0,1,REC1004,2026-01-29,2026-01-30,2026-02-05,2026-02-07,ANA CAROLINA,2026-03-07 00:00:00,NaN,77,NaN
4,2026,1,I,RECIFE ANTIGO,RECIFE ANTIGO,EMERSON MELO/77.110-0,1,REC1005,2026-01-29,2026-01-30,2026-02-05,2026-02-07,ANA CAROLINA,2026-03-07 00:00:00,NaN,88,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31450,2026,12,VIII,COHAB,COHAB 4,FLÁVIO JORGE/78.367-0,719,COH8122,2026-07-13,2026-07-15,2026-07-15,2026-07-18,FABIANE,2026-07-20 00:00:00,2026-07-31 00:00:00,0,NaN
31451,2026,12,VIII,COHAB,COHAB 4,DARCIELE CABRAL/130.177-2,713,COH8111,2026-07-13,2026-07-15,2026-07-15,2026-07-18,FABIANE,2026-07-20 00:00:00,2026-07-31 00:00:00,433,NaN
31452,2026,12,VIII,COHAB,COHAB 4,DARCIELE CABRAL/130.177-2,739,COH8114,2026-07-13,2026-07-15,2026-07-15,2026-07-18,FABIANE,2026-07-20 00:00:00,2026-07-31 00:00:00,308,NaN
31453,2026,12,VIII,COHAB,COHAB 4,DARCIELE CABRAL/130.177-2,797,COH8117,2026-07-13,2026-07-15,2026-07-15,2026-07-18,FABIANE,2026-07-20 00:00:00,2026-07-31 00:00:00,95,NaN
31454,2026,12,VIII,COHAB,COHAB 4,DARCIELE CABRAL/130.177-2,825,COH8130,2026-07-13,2026-07-15,2026-07-15,2026-07-18,FABIANE,2026-07-20 00:00:00,2026-07-31 00:00:00,62,NaN

In [ ]:
db = sqlite3.connect("database.db")
ovitrampas

,Ano,CICLOS,DS,BAIRRO,BAIRRO_AREA,AGENTE / MATRICULA,QT,ID_OVT,DT_COLETA,DT_ENTREGA_APOIO,DT_ENTREGA_LAB,DT_LEITURA,NM_TEC_LAB,DT_DIG,DT_ENVIO_DS,N_OVOS,OBS
0,2026,1,I,RECIFE ANTIGO,RECIFE ANTIGO,EMERSON MELO/77.110-0,1,REC1001,2026-01-29,2026-01-30,2026-02-05,2026-02-07,ANA CAROLINA,2026-03-07 00:00:00,NaN,16,NaN
1,2026,1,I,RECIFE ANTIGO,RECIFE ANTIGO,EMERSON MELO/77.110-0,1,REC1002,2026-01-29,2026-01-30,2026-02-05,2026-02-07,ANA CAROLINA,2026-03-07 00:00:00,NaN,14,NaN
2,2026,1,I,RECIFE ANTIGO,RECIFE ANTIGO,EMERSON MELO/77.110-0,1,REC1003,2026-01-29,2026-01-30,2026-02-05,2026-02-07,ANA CAROLINA,2026-03-07 00:00:00,NaN,83,NaN
3,2026,1,I,RECIFE ANTIGO,RECIFE ANTIGO,EMERSON MELO/77.110-0,1,REC1004,2026-01-29,2026-01-30,2026-02-05,2026-02-07,ANA CAROLINA,2026-03-07 00:00:00,NaN,77,NaN
4,2026,1,I,RECIFE ANTIGO,RECIFE ANTIGO,EMERSON MELO/77.110-0,1,REC1005,2026-01-29,2026-01-30,2026-02-05,2026-02-07,ANA CAROLINA,2026-03-07 00:00:00,NaN,88,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31450,2026,12,VIII,COHAB,COHAB 4,FLÁVIO JORGE/78.367-0,719,COH8122,2026-07-13,2026-07-15,2026-07-15,2026-07-18,FABIANE,2026-07-20 00:00:00,2026-07-31 00:00:00,0,NaN
31451,2026,12,VIII,COHAB,COHAB 4,DARCIELE CABRAL/130.177-2,713,COH8111,2026-07-13,2026-07-15,2026-07-15,2026-07-18,FABIANE,2026-07-20 00:00:00,2026-07-31 00:00:00,433,NaN
31452,2026,12,VIII,COHAB,COHAB 4,DARCIELE CABRAL/130.177-2,739,COH8114,2026-07-13,2026-07-15,2026-07-15,2026-07-18,FABIANE,2026-07-20 00:00:00,2026-07-31 00:00:00,308,NaN
31453,2026,12,VIII,COHAB,COHAB 4,DARCIELE CABRAL/130.177-2,797,COH8117,2026-07-13,2026-07-15,2026-07-15,2026-07-18,FABIANE,2026-07-20 00:00:00,2026-07-31 00:00:00,95,NaN
31454,2026,12,VIII,COHAB,COHAB 4,DARCIELE CABRAL/130.177-2,825,COH8130,2026-07-13,2026-07-15,2026-07-15,2026-07-18,FABIANE,2026-07-20 00:00:00,2026-07-31 00:00:00,62,NaN