In [ ]:
from pymongo import MongoClient
from pymongo.server_api import ServerApi
from dotenv import load_dotenv
import pandas
import os
import json

uri = "mongodb+srv://DB_USER:DB_PASSWORD@cluster0.qoks7uh.mongodb.net/?appName=Cluster0"
# Create a new client and connect to the server
client = MongoClient(os.environ["MONGO_URL"], server_api=ServerApi('1'))
# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

db = client['dados_ibge']
dados_ibge = db['dados_ibge'].find()
print(dados_ibge[1]['resultados'][0]['series'][0]['serie'])

serie = dados_ibge[1]['resultados'][0]['series'][0]['serie']
df = pandas.DataFrame.from_dict(serie, orient='index',columns=['valor'])
df.index.name = 'periodo'
df = df.reset_index()
df.head()

Pinged your deployment. You successfully connected to MongoDB!
{'201201': '9.6', '201202': '8.3', '201203': '9.4', '201204': '9.2', '201301': '10.7', '201302': '9.7', '201303': '8.5', '201304': '7.4', '201401': '8.8', '201402': '8.0', '201403': '8.5', '201404': '7.7', '201501': '8.2', '201502': '9.2', '201503': '11.3', '201504': '11.1', '201601': '13.4', '201602': '14.2', '201603': '15.5', '201604': '15.9', '201701': '17.3', '201702': '19.0', '201703': '18.1', '201704': '17.0', '201801': '17.9', '201802': '17.1', '201803': '17.0', '201804': '15.6', '201901': '16.3', '201902': '16.1', '201903': '16.0', '201904': '14.2', '202001': '14.8', '202002': '...', '202003': '...', '202004': '...', '202101': '...', '202102': '...', '202103': '...', '202104': '...', '202201': '...', '202202': '13.6', '202203': '14.0', '202204': '12.3', '202301': '14.1', '202302': '14.2', '202303': '13.3', '202304': '12.0', '202401': '12.4', '202402': '11.6', '202403': '10.6', '202404': '10.3', '202501': '11.6', '202502': '10.4', '202503': '10.0', '202504': '8.8', '202601': '9.2', '202602': '8.3'}

  periodo valor
0  201201   9.6
1  201202   8.3
2  201203   9.4
3  201204   9.2
4  201301  10.7

In [19]:
print(df)

   periodo valor
0   201201   9.6
1   201202   8.3
2   201203   9.4
3   201204   9.2
4   201301  10.7
5   201302   9.7
6   201303   8.5
7   201304   7.4
8   201401   8.8
9   201402   8.0
10  201403   8.5
11  201404   7.7
12  201501   8.2
13  201502   9.2
14  201503  11.3
15  201504  11.1
16  201601  13.4
17  201602  14.2
18  201603  15.5
19  201604  15.9
20  201701  17.3
21  201702  19.0
22  201703  18.1
23  201704  17.0
24  201801  17.9
25  201802  17.1
26  201803  17.0
27  201804  15.6
28  201901  16.3
29  201902  16.1
30  201903  16.0
31  201904  14.2
32  202001  14.8
33  202002   ...
34  202003   ...
35  202004   ...
36  202101   ...
37  202102   ...
38  202103   ...
39  202104   ...
40  202201   ...
41  202202  13.6
42  202203  14.0
43  202204  12.3
44  202301  14.1
45  202302  14.2
46  202303  13.3
47  202304  12.0
48  202401  12.4
49  202402  11.6
50  202403  10.6
51  202404  10.3
52  202501  11.6
53  202502  10.4
54  202503  10.0
55  202504   8.8
56  202601   9.2
57  202602   8.3

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   periodo  58 non-null     str
 1   valor    58 non-null     str
dtypes: str(2)
memory usage: 1.0 KB

In [26]:
df['valor'] = df['valor'].replace('...','0')
df['valor'] = df['valor'].astype(float)
df['periodo']=df['periodo'].astype(str)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   periodo  58 non-null     str
 1   valor    58 non-null     float64
dtypes: float64(1), str(1)
memory usage: 1.0 KB

In [ ]:
df['ano'] = df['periodo'].str[:4]
df['tri'] = df['periodo'].str[-1:]
df['periodo'] = pandas.PeriodIndex(df['ano']+'Q'+df['tri'], freq='Q')


df

   periodo  valor   ano tri
0   2012Q1    9.6  2012   1
1   2012Q2    8.3  2012   2
2   2012Q3    9.4  2012   3
3   2012Q4    9.2  2012   4
4   2013Q1   10.7  2013   1
5   2013Q2    9.7  2013   2
6   2013Q3    8.5  2013   3
7   2013Q4    7.4  2013   4
8   2014Q1    8.8  2014   1
9   2014Q2    8.0  2014   2
10  2014Q3    8.5  2014   3
11  2014Q4    7.7  2014   4
12  2015Q1    8.2  2015   1
13  2015Q2    9.2  2015   2
14  2015Q3   11.3  2015   3
15  2015Q4   11.1  2015   4
16  2016Q1   13.4  2016   1
17  2016Q2   14.2  2016   2
18  2016Q3   15.5  2016   3
19  2016Q4   15.9  2016   4
20  2017Q1   17.3  2017   1
21  2017Q2   19.0  2017   2
22  2017Q3   18.1  2017   3
23  2017Q4   17.0  2017   4
24  2018Q1   17.9  2018   1
25  2018Q2   17.1  2018   2
26  2018Q3   17.0  2018   3
27  2018Q4   15.6  2018   4
28  2019Q1   16.3  2019   1
29  2019Q2   16.1  2019   2
30  2019Q3   16.0  2019   3
31  2019Q4   14.2  2019   4
32  2020Q1   14.8  2020   1
33  2020Q2    0.0  2020   2
34  2020Q3    0.0  2020   3
35  2020Q4    0.0  2020   4
36  2021Q1    0.0  2021   1
37  2021Q2    0.0  2021   2
38  2021Q3    0.0  2021   3
39  2021Q4    0.0  2021   4
40  2022Q1    0.0  2022   1
41  2022Q2   13.6  2022   2
42  2022Q3   14.0  2022   3
43  2022Q4   12.3  2022   4
44  2023Q1   14.1  2023   1
45  2023Q2   14.2  2023   2
46  2023Q3   13.3  2023   3
47  2023Q4   12.0  2023   4
48  2024Q1   12.4  2024   1
49  2024Q2   11.6  2024   2
50  2024Q3   10.6  2024   3
51  2024Q4   10.3  2024   4
52  2025Q1   11.6  2025   1
53  2025Q2   10.4  2025   2
54  2025Q3   10.0  2025   3
55  2025Q4    8.8  2025   4
56  2026Q1    9.2  2026   1
57  2026Q2    8.3  2026   2

In [28]:
df['periodo'] = df['periodo'].dt.to_timestamp()
df

      periodo  valor   ano tri
0  2012-01-01    9.6  2012   1
1  2012-04-01    8.3  2012   2
2  2012-07-01    9.4  2012   3
3  2012-10-01    9.2  2012   4
4  2013-01-01   10.7  2013   1
5  2013-04-01    9.7  2013   2
6  2013-07-01    8.5  2013   3
7  2013-10-01    7.4  2013   4
8  2014-01-01    8.8  2014   1
9  2014-04-01    8.0  2014   2
10 2014-07-01    8.5  2014   3
11 2014-10-01    7.7  2014   4
12 2015-01-01    8.2  2015   1
13 2015-04-01    9.2  2015   2
14 2015-07-01   11.3  2015   3
15 2015-10-01   11.1  2015   4
16 2016-01-01   13.4  2016   1
17 2016-04-01   14.2  2016   2
18 2016-07-01   15.5  2016   3
19 2016-10-01   15.9  2016   4
20 2017-01-01   17.3  2017   1
21 2017-04-01   19.0  2017   2
22 2017-07-01   18.1  2017   3
23 2017-10-01   17.0  2017   4
24 2018-01-01   17.9  2018   1
25 2018-04-01   17.1  2018   2
26 2018-07-01   17.0  2018   3
27 2018-10-01   15.6  2018   4
28 2019-01-01   16.3  2019   1
29 2019-04-01   16.1  2019   2
30 2019-07-01   16.0  2019   3
31 2019-10-01   14.2  2019   4
32 2020-01-01   14.8  2020   1
33 2020-04-01    0.0  2020   2
34 2020-07-01    0.0  2020   3
35 2020-10-01    0.0  2020   4
36 2021-01-01    0.0  2021   1
37 2021-04-01    0.0  2021   2
38 2021-07-01    0.0  2021   3
39 2021-10-01    0.0  2021   4
40 2022-01-01    0.0  2022   1
41 2022-04-01   13.6  2022   2
42 2022-07-01   14.0  2022   3
43 2022-10-01   12.3  2022   4
44 2023-01-01   14.1  2023   1
45 2023-04-01   14.2  2023   2
46 2023-07-01   13.3  2023   3
47 2023-10-01   12.0  2023   4
48 2024-01-01   12.4  2024   1
49 2024-04-01   11.6  2024   2
50 2024-07-01   10.6  2024   3
51 2024-10-01   10.3  2024   4
52 2025-01-01   11.6  2025   1
53 2025-04-01   10.4  2025   2
54 2025-07-01   10.0  2025   3
55 2025-10-01    8.8  2025   4
56 2026-01-01    9.2  2026   1
57 2026-04-01    8.3  2026   2

In [29]:
import sqlite3

connect = sqlite3.connect("IBGE.db")
df.to_sql("pnadc_total",con=connect,if_exists="replace", index=False)
connect.close()